name: Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GotoCharTimer
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm

    - name: Install Dependencies
      run: npm install

    - name: New Release
      run: npm version patch

    - name: Publish to VSCode Marketplace
      run: vsce publish -p ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
