name: Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GotoCharTimer
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: npm

    - name: Install Dependencies
      run: npm install

    - name: Publish to VSCode Marketplace
      env:
        VSCODE_MARKETPLACE_TOKEN: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
      run: |
        git config --global user.email "bot@rgkirch.github.io"
        git config --global user.name "bot"
        npx vsce publish patch -p $VSCODE_MARKETPLACE_TOKEN
        git push origin master

