name: Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GotoCharTimer
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm

    - name: Install Dependencies
      run: npm install

    - name: New Release
      run: |
        git config --global user.email "bot@rgkirch.github.io"
        git config --global user.name "bot"
        npm version patch
        git push origin master
      
    - name: Publish to VSCode Marketplace
      env:
        VSCODE_MARKETPLACE_TOKEN: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
      run: npx vsce publish -p $VSCODE_MARKETPLACE_TOKEN

